In [1]:
import numpy as np

# 3

In [ ]:
from time import time

In [ ]:
A = np.random.normal(loc=0.,
                     scale=1.,
                     size=(5000,5000))
b = np.random.normal(loc=0.,
                     scale=1.,
                     size=(5000,1))

Solve $\mathbf{A} \boldsymbol{x} = \boldsymbol{b}$ with `solve`

In [ ]:
start = time()
_ = np.linalg.solve(A, b)
end = time()

print('spent:', end-start)

spent: 3.1150851249694824


Solve $\mathbf{A} \boldsymbol{x} = \boldsymbol{b}$ with `inv`

In [ ]:
start = time()
# `@` is a shorthand for `np.matmul`
_ = np.linalg.inv(A) @ b
end = time()

print('spent:', end-start)

spent: 11.219438552856445


## Conclusion

Prioritize `solve` against `inv` when solving square matrix linear systems.

# 4

In [2]:
A = np.random.normal(loc=0.,
                     scale=1.,
                     size=(100,100))

In [3]:
U, S, Vt = np.linalg.svd(A)
Sigma = np.diag(S)

There is trivial difference between $\mathbf{A}^\dagger$ and $\mathbf{V} \mathbf{\Sigma}^\dagger \mathbf{U}^{\mathsf{T}}$ since they are determined numerically. They deviate from each other when the threshold falls below `1e-7`.

In [4]:
False in (Vt.T @ np.linalg.pinv(Sigma) @ U.T - np.linalg.pinv(A) < 1e-6)

False

# 7

In [ ]:
a = np.random.normal(loc=0.,
                     scale=1.,
                     size=500)
b = np.random.normal(loc=0.,
                     scale=1.,
                     size=500)

## (a)

In [ ]:
np.square(np.linalg.norm(a))

500.7376584630145

My own implementation

In [ ]:
np.sum(a * a)

500.7376584630145

## (b)

In [ ]:
np.square(np.linalg.norm(a - b)) / 500

1.8501932513981907

# 10

## (a)

In [ ]:
def generate_matrix(n):
    A = np.random.normal(loc=0.,
                         scale=1,
                         size=(n,n))
    
    return A @ A.T / n

$$
\lim_{n \to ∞} \frac{1}{n} \mathbf{A}_{n \times n} \mathbf{A}_{n \times n}^\mathsf{T} = \mathbf{I}_{n \times n}
$$

In [ ]:
generate_matrix(10)

array([[ 1.61303464,  0.32606821, -0.27338126, -0.04090386,  0.10554306,
         0.81639868, -0.80663109, -0.27621728, -0.20926759,  0.95005824],
       [ 0.32606821,  1.21810092, -0.17426875, -0.1854334 ,  0.48531716,
        -0.32236305, -0.16750074,  0.12687946,  0.46107913,  0.08798947],
       [-0.27338126, -0.17426875,  1.36590405,  0.32960568,  0.10050751,
        -0.445838  ,  0.26457277, -0.19343991,  0.54584419, -0.21568079],
       [-0.04090386, -0.1854334 ,  0.32960568,  1.05988711, -0.16408272,
         0.9225742 ,  0.06376235,  0.32061476, -0.5452233 ,  0.5265089 ],
       [ 0.10554306,  0.48531716,  0.10050751, -0.16408272,  0.55737383,
        -0.15006045, -0.33744167,  0.07428361,  0.15528469, -0.06795785],
       [ 0.81639868, -0.32236305, -0.445838  ,  0.9225742 , -0.15006045,
         2.09381798, -0.53490676,  0.15152753, -0.97881204,  0.81102528],
       [-0.80663109, -0.16750074,  0.26457277,  0.06376235, -0.33744167,
        -0.53490676,  1.53286776, -0.21423272

In [ ]:
generate_matrix(100)

array([[ 8.43041082e-01, -9.78567910e-02, -8.33026848e-02, ...,
         2.38239816e-01, -5.91184065e-02, -1.35133234e-02],
       [-9.78567910e-02,  9.14692168e-01, -1.79884781e-01, ...,
        -5.91122511e-02,  2.16744088e-02, -8.22158439e-02],
       [-8.33026848e-02, -1.79884781e-01,  1.09914255e+00, ...,
         7.53532395e-03, -3.50233172e-02, -1.16229297e-01],
       ...,
       [ 2.38239816e-01, -5.91122511e-02,  7.53532395e-03, ...,
         9.38279826e-01,  8.95434870e-02,  1.10402620e-03],
       [-5.91184065e-02,  2.16744088e-02, -3.50233172e-02, ...,
         8.95434870e-02,  1.15636398e+00,  3.52259508e-03],
       [-1.35133234e-02, -8.22158439e-02, -1.16229297e-01, ...,
         1.10402620e-03,  3.52259508e-03,  8.93189067e-01]])

In [ ]:
generate_matrix(1000)

array([[ 0.98500618, -0.02876766, -0.04243413, ..., -0.04969708,
         0.01766531,  0.00440646],
       [-0.02876766,  1.00959411,  0.07267103, ..., -0.04278422,
        -0.01227168, -0.03536624],
       [-0.04243413,  0.07267103,  0.96802923, ..., -0.00743289,
        -0.02964955,  0.02773229],
       ...,
       [-0.04969708, -0.04278422, -0.00743289, ...,  0.99397877,
        -0.04377132, -0.04786017],
       [ 0.01766531, -0.01227168, -0.02964955, ..., -0.04377132,
         0.88121368, -0.00107025],
       [ 0.00440646, -0.03536624,  0.02773229, ..., -0.04786017,
        -0.00107025,  0.93919165]])

## (b)

Stack $\mathbf{A}_1, \mathbf{A}_2, \dots, \mathbf{A}_m$ in a 3D fashion and initialize them simultaneously.

In [ ]:
def get_sum(m, n=10):
    A_stack = np.random.normal(loc=0.,
                               scale=1.,
                               size=(n,n, m))
    return np.sum(A_stack * A_stack, axis=2) / m

$$
\lim_{m \to \infty} \frac{1}{m} \sum_{i=1}^m \mathbf{A}_i^2 = \mathbf{J}_{10 \times 10}
$$
where $\mathbf{J}$ is a matrix with $1$ as all entries

In [ ]:
get_sum(10)

array([[1.22596484, 0.32227597, 1.43641751, 0.52228329, 1.39715796,
        1.34041288, 0.8355501 , 0.99173622, 1.32704468, 1.18656558],
       [0.4284045 , 0.86042057, 0.95917646, 0.6858166 , 1.38590202,
        1.06582004, 1.10707997, 0.85959531, 0.80382377, 1.14844754],
       [1.42115831, 2.53211933, 0.72616742, 0.53158662, 0.33344917,
        0.78860929, 0.50869813, 0.94563216, 1.48439543, 1.43953541],
       [0.63871438, 1.1112049 , 1.32692595, 0.94027341, 0.7172683 ,
        0.76114131, 1.1605897 , 0.5394559 , 1.50509274, 2.16654848],
       [0.80509212, 1.41609605, 0.70912681, 0.88540425, 0.7500674 ,
        0.90668785, 1.0040489 , 2.18996686, 0.51699775, 1.35619412],
       [0.94469419, 0.9250057 , 0.8021962 , 1.20692883, 0.86153759,
        0.60478697, 1.06651746, 1.97566713, 1.40490189, 1.45775706],
       [1.67586735, 0.88213793, 0.79605552, 0.90899144, 1.40287182,
        0.93524137, 1.43939856, 1.04436507, 0.63488115, 1.27176974],
       [1.19900683, 0.56894104, 1.6823913

In [ ]:
get_sum(100)

array([[0.95193328, 0.92657413, 1.12728851, 0.7156137 , 1.12183717,
        0.9820182 , 1.12166552, 1.01264017, 0.87611235, 1.3299511 ],
       [0.94409054, 1.0342169 , 0.91470533, 0.97826372, 0.85478431,
        1.18668232, 1.2529265 , 1.27720511, 0.88655266, 1.16996123],
       [0.99448825, 0.71365572, 0.94951833, 1.29230673, 0.86533127,
        1.05403006, 0.84077499, 1.06481177, 1.0225489 , 1.05285525],
       [0.87611433, 0.84044428, 1.27178582, 0.99525702, 1.02376722,
        0.95556941, 0.80508041, 1.1509754 , 0.97238528, 0.92535725],
       [1.17333505, 0.96249601, 1.05076467, 1.1831391 , 1.00005416,
        0.9829379 , 0.87689673, 1.13463093, 1.14894276, 1.07532458],
       [1.06995532, 1.08228579, 0.94064769, 0.88959714, 1.00233155,
        1.00538412, 1.34281086, 1.13836203, 1.25904981, 0.77010965],
       [0.95290603, 0.91827588, 0.89229373, 0.86063865, 1.14767681,
        0.84924843, 0.85837774, 1.18619197, 1.15670752, 1.09798706],
       [1.01583073, 1.0902546 , 0.9630443

In [ ]:
get_sum(1000)

array([[0.97297283, 0.91708381, 0.99113582, 1.02986991, 0.97813579,
        0.96616212, 1.08048155, 0.9857094 , 1.00825049, 0.92089455],
       [0.90326547, 0.95969782, 1.03694179, 1.00088547, 0.99765254,
        0.96419812, 1.07320683, 0.93282208, 0.97259449, 0.92158757],
       [1.02603345, 0.94460727, 0.97534008, 1.04203785, 0.98611667,
        0.97126229, 0.94017801, 1.01162351, 0.97578855, 0.92896404],
       [0.93881817, 1.05353946, 0.91117764, 1.08373092, 1.03981153,
        0.91200108, 0.99223255, 0.9820305 , 0.96072209, 0.99870281],
       [1.08702124, 0.94844191, 0.96637633, 1.06292181, 1.03684823,
        1.02352936, 0.94075118, 0.99564275, 1.03683417, 0.98582669],
       [1.03735946, 0.99372364, 1.04321944, 1.03144312, 0.89384769,
        0.96733457, 0.97880142, 0.95010308, 0.96706585, 1.06401647],
       [0.94385557, 0.97537574, 0.96440664, 0.99913593, 0.98353679,
        1.0179965 , 1.04677632, 1.05847985, 0.95711832, 0.98135122],
       [0.99364475, 0.96230817, 0.9648688